#!/bin/sh
PATH=/bin:/usr/bin:/usr/local/bin
export PATH

scripts/CVSMake

cvs2cl.pl

CDIR=`pwd`
CDIR_BNAME=`basename $CDIR`
cd ..
tar --exclude CVS --exclude .cvsignore --exclude autom4te.cache -cvzf ${CDIR_BNAME}.tar.gz $CDIR_BNAME
cd -
